version: '3.1'

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin123
      INFLUXDB_DB: mydb
    volumes:
      - influxdb-data:/var/lib/influxdb2

volumes:
  influxdb-data:
    driver: local
